description: Template for Microsoft Windows Server 2022 VM. A PVC with the Windows
  disk image must be available.
name: windows2k22-server-large
tags: hidden,kubevirt,virtualmachine,windows
version: v0.0.1
